language: c

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libjansson-dev
    - valgrind
    - cppcheck
    - lcov
    - gcc-6


before_install:
  - gem install coveralls-lcov
  - git submodule update test/cmocka
  - cd test
  - mkdir cmocka_build ~/libs && cd cmocka_build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=~/libs ../cmocka
  - make -j 4
  - make install
  - export LD_LIBRARY_PATH=~libs:${LD_LIBRARY_PATH}
  - cd ../..

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi

matrix:
  include:
    - compiler: clang
    - compiler: gcc

script:
  - export SOURCE=$(pwd) && ./buildscript.sh

notifications:
  email: false
