language: c

sudo: true

matrix:
  include:
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.6
        - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
        - clang-3.6
        - libjansson-dev
        - valgrind
        - cppcheck
        - lcov
        - cmake
        - cmake-data
  - compiler: gcc-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
        - gcc-6
        - g++-6
        - libjansson-dev
        - valgrind
        - cppcheck
        - lcov
        - cmake
        - cmake-data
# Temporarily disabled due to slow performance and problems with Raspbian
# chroot (https://travis-ci.org/PJK/libcbor/jobs/281748138)
#  - env: ARCH=arm
#    addons:
#      apt:
#        sources:
#        - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
#        packages:
#        - gcc-arm-linux-gnueabihf
#        - libc6-dev-armhf-cross
#        - cmake
#        - cmake-data

script:
  - "bash -ex .travis-qemu.sh"

notifications:
  email: false
