language: c

sudo: false

addons:
  apt:
    sources:
    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
    - libjansson-dev
    - valgrind
    - cppcheck
    - lcov
    - cmake
    - cmake-data

before_install:
  - gem install coveralls-lcov
  - pushd $HOME
  - git clone git://git.cryptomilk.org/projects/cmocka.git
  - mkdir cmocka_build && cd cmocka_build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME ../cmocka
  - make -j 2
  - make install
# Confuses CMake search
  - cd ..
  - rm -rf cmocka cmocka_build
  - popd

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi

matrix:
  include:
    - compiler: clang
     addons:
       apt:
         sources:
         - llvm-toolchain-precise-3.6
         packages:
         - clang-3.6
     env: CC="clang-3.6" CXX="clang++-3.6"

    - compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-6
      env: CC="gcc-6" CXX="g++-6"



script:
  - export SOURCE=$(pwd) && ./buildscript.sh

notifications:
  email: false
