language: c

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
    - libjansson-dev
    - valgrind
    - cppcheck
    - lcov
    - gcc-6
    - cmake
    - cmake-data

before_install:
  - gem install coveralls-lcov
  - pushd $HOME
  - git clone git://git.cryptomilk.org/projects/cmocka.git
  - mkdir cmocka_build && cd cmocka_build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME ../cmocka
  - make -j 2
  - make install
# Confuses CMake search
  - cd ..
  - rm -rf cmocka cmocka_build
  - popd

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi

matrix:
  include:
    - compiler: clang
    - compiler: gcc

script:
  - export SOURCE=$(pwd) && ./buildscript.sh

notifications:
  email: false
