language: c

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov
  - sudo apt-get update -qq
  - sudo apt-get -qq install gcc-4.9 libjansson-dev valgrind cppcheck
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90
  - git submodule update test/cmocka
  - cd test
  - mkdir cmocka_build && cd cmocka_build
  - cmake ../cmocka
  - make -j 4
  - sudo make install
  - export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH} 
  - cd ../..

matrix:
  include:
    - compiler: clang
      env: CUSTOM_ALLOC=ON
    - compiler: clang
      env: CUSTOM_ALLOC=OFF
    - compiler: gcc
      env: CUSTOM_ALLOC=OFF

script:
  - export SOURCE=$(pwd) && ./buildscript.sh

notifications:
  email: false
