language: c

sudo: true

before_install:
  - gem install coveralls-lcov
  - pushd $HOME
  - git clone git://git.cryptomilk.org/projects/cmocka.git
  - mkdir cmocka_build && cd cmocka_build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME ../cmocka
  - make -j 2
  - make install
# Confuses CMake search
  - cd ..
  - rm -rf cmocka cmocka_build
  - popd

matrix:
  include:
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.6
        - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
        - clang-3.6
        - libjansson-dev
        - valgrind
        - cppcheck
        - lcov
        - cmake
        - cmake-data
    env: CC="clang-3.6" CXX="clang++-3.6"
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
        - gcc-6
        - g++-6
        - libjansson-dev
        - valgrind
        - cppcheck
        - lcov
        - cmake
        - cmake-data
    env: CC="gcc-6" CXX="g++-6"
  - env: ARCH=arm



script:
  - "bash -ex .travis-qemu.sh"
  - export SOURCE=$(pwd) && ./buildscript.sh

notifications:
  email: false
