image: Visual Studio 2015
version: '{build}'

branches:
  except:
    - gh-pages

platform: x64


environment:
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"

# Via https://github.com/apitrace/apitrace/blob/master/appveyor.yml

before_build:
- cmake -H. -Bbuild -G "%CMAKE_GENERATOR%"

build_script:
- if "%APPVEYOR_REPO_TAG%"=="true" (set CONFIGURATION=RelWithDebInfo) else (set CONFIGURATION=Debug)
- cmake --build build --config "%CONFIGURATION%"

after_build:
- cmake --build build --config "%CONFIGURATION%" --target check
- cmake --build build --config "%CONFIGURATION%" --target package